version: '3'

services:
  backend:
    build: ./
    depends_on:
      - mysql
    restart: always
    volumes:
      - /app/node_modules
      - ./:/app
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users_db
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
  migration:
    build:
      context: ./
    command:
      [
        "npm",
        "run",
        "migrate"
      ]
    depends_on:
      - mysql
      - backend
    restart: on-failure
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "80:80"
    depends_on:
      - mysql
      - backend
      - migration
volumes:
  mysql_data: